### ISSUE TITLE
merge action can not work.

### ISSUE THREAD

**Issue by snowyu** [ngx-rocket/core#17]
see this branch of the addon: https://github.com/snowyu/generator-pre-commit-addon.js/tree/bug/merge

**Comment by snowyu** [comment]
I have to use the `writing` event to manual merge deeply.

**Comment by sinedied** [comment]
I just tested with your repo and commented the `writing` method in the branch you specified, and it worked as expected merging the `package.json` file?

Be careful when overriding base generator methods (`prompting` and `writing`) as you need to call the original method with `super.<method>` to make sure the original behaviors still works.
I'll add a note on the docs about this.

**Comment by snowyu** [comment]
It's worked well after removing `writing` method.

But `super.writing()` in `writing` method only, It reports a confiction:

```
 conflict package.json
```

**Comment by sinedied** [comment]
The original `writing()` method returns a promise, so you need to return it to make it work correctly:
```js
writing() {
   return super.writing();
}
```
Should work the same as without the method

**Comment by snowyu** [comment]
yeah,  I did not expect the result to be a promise.
