### ISSUE TITLE
Prompt asks information twice

### ISSUE THREAD

**Issue by AlexandreKueny** [ngx-rocket/core#25]
I'm building my own standalone generator based on @gnx-rocket/core.
When I launch it, I'm beeing asked the same questions twice.

Here is an example:
![capture-addon](https://user-images.githubusercontent.com/4974911/91444310-d96ef780-e874-11ea-8174-51b89b4db5a0.png)

**Comment by sinedied** [comment]
Thanks for the report, seems to be related: https://github.com/ngx-rocket/generator-ngx-rocket/issues/566
